### ISSUE TITLE
Arbeitsverzeichnis

### ISSUE THREAD

**Issue by RuthNvll** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18#1]
Beim Setzen des Arbeitsverzeichnisses und dem Arbeiten in Ordnerstrukturen bietet es sich an, auf Leerzeichen sowie Punkte und Sonderzeichen zu vermeiden, da R damit je nach dem Probleme haben kann. 

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18/blob/3bb88e4d531416198e0c6921745d3fef123f7d6a/Assignment_01_Simon.Rmd#L21

**Comment by BenR32** [comment]
Danke für den Hinweis
