### ISSUE TITLE
Teammembers

### ISSUE THREAD

**Issue by RuthNvll** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18#4]
Hat dies nicht das Team gemeinsam gemacht???

https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18/blob/3bb88e4d531416198e0c6921745d3fef123f7d6a/Assignment_01_Simon.Rmd#L3

**Comment by CSeimn** [comment]
Wurde gemeinsam gelöst, aber nur von einer Person (versehentlich) unter eigenem Namen hochgeladen.
