### ISSUE TITLE
Feedback Assignment01

### ISSUE THREAD

**Issue by alinaBau** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18#5]
Ihr hättet vieleicht noch zeigen können , wie ihr das working environment gesetzt habt. 
Habt Ihr eine Lösung gefunden, um mehrer Bilder zu plotten?

**Comment by BenR32** [comment]
Jetzt ja inzwischen über source( )
Das mit den mehreren Bildern wollten wir eigentlich in einer for-Schleife lösen, allerdings gibt es da leider Probleme mit der Namensgebung
