### ISSUE TITLE
Feedback Assighnment02

### ISSUE THREAD

**Issue by johnfurie** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18#6]
We can't find a assignment file (RMD & Markdown) in your doc folder. 
the src code for assignment02 looks ok. The filepaths should be linked by the (~/edu) folder we created previously. To save some space it's a better option to loop the brick(raster) insted of copying the row . The explanation to the single working steps is good

**Comment by BenR32** [comment]
Thanks for your feedback. We could not execute the RMD, because of memory issues too. A solution would be the processing on the computers of the university. 
Now we have changed the working directory with the new link.
The next step will be the implementation of the loops.
