### ISSUE TITLE
RAM Issues

### ISSUE THREAD

**Issue by eikeschott** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18#7]
https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-bjcm_rs_18/blob/d5456c8e9ab1bee632dce9c5a9df1e6d3119a6ea/src/Processing_MOF_Vers_2.R#L12

there is no need to extract all values at this point. (thats the reason for your high RAM usage as well)
It's totally fine to store the images as a list like so:

```
imagelist <- list()
for(i in imagelist){
  imagelist [[i]] <- brick(paste0("~/edu/mpg-envinsys-plygrnd/data/aerial/org/", i))
}
```

**Comment by CSeimn** [comment]
Thank you! 
I thought, this was needed.
